#!/usr/bin/env ruby
#^syntax detection

site :opscode

cookbook 'apt'
cookbook 'ohai'
cookbook 'subversion'
cookbook 'git'
cookbook 'build-essential'

# Load site-cookbooks
Dir.glob('./site-cookbooks/*').each do |path|
  cookbook File.basename(path), :path => path
end
