# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  
  config.vm.box = "precise32"
  config.vm.box_url = "http://files.vagrantup.com/precise32.box"

  config.vm.network :private_network, ip: "192.168.33.11"
  config.vm.network :public_network

  # Map the project directories into the VM, that way local edits will show up! 
  config.vm.synced_folder "scripts", "/var/scripts"
  config.vm.synced_folder "project/", "/opt/os"

  # Bootstrap the VM to get the latest version of Chef installed
  config.vm.provision :shell, :inline => 'bash /var/scripts/bootstrap.sh'

  config.berkshelf.enabled = true

  config.vm.provision :chef_solo do |chef|
     chef.cookbooks_path = ["./cookbooks", "./site-cookbooks"]
     chef.roles_path = "./roles"
     chef.data_bags_path = "./data_bags"
     chef.add_role "base" 
     chef.add_role "gcc32"
     chef.add_role "gcc64"
  end

end
